/* SPDX-License-Identifier: GPL-2.0
 *
 * kmod_offsets.h - per-kernel layout constants for rwbridge.
 *
 * GENERATED by CI for each target kernel (.github/workflows/build.yml) from
 * that kernel's kheaders / prepared source tree (one set of values per GKI
 * major: 5.10 / 5.15 / 6.1 / 6.6 / 6.12 / 6.18, + the vendor 5.15 build).
 *
 * These are NOT part of the GKI stable-KMI surface and vary per kernel major,
 * so a single .ko cannot serve all majors: build.sh bundles one .ko per major
 * and run.sh lets the kernel's vermagic check pick the match.
 *
 * Derivation (same method the BlueStacks 5.15 values came from):
 *   LXGR_OFF_TASKS   offsetof(struct task_struct, tasks)   // struct list_head
 *   LXGR_OFF_PID     task_struct field whose value (low 32) is the pid
 *   LXGR_OFF_MM      offsetof(struct task_struct, mm)        // struct mm_struct *
 *   LXGR_OFF_COMM    offsetof(struct task_struct, comm)      // char[16]
 *   LXGR_OFF_MM_PGD  offsetof(struct mm_struct, pgd)
 *   PAGE_OFFSET      linear-map base from CONFIG_ARM64_VA_BITS (39b -> 0xffffff8..0)
 *   USER_VA_TOP      1 << VA_BITS  (user-range ceiling; 39b -> 0x8000000000)
 *
 * Defaults below are VERIFIED for the BlueStacks emulator build:
 *   5.15.137-v5.21.770-optimizations-5.21.771.4051  (CONFIG_ARM64_VA_BITS=39)
 * Do NOT assume them on another kernel major; CI writes this file per build.
 */
#ifndef LXGR_KMOD_OFFSETS_H
#define LXGR_KMOD_OFFSETS_H

#define LXGR_OFF_TASKS   1232UL
#define LXGR_OFF_PID     1496UL
#define LXGR_OFF_MM      1312UL
#define LXGR_OFF_COMM    1960UL
#define LXGR_OFF_MM_PGD  64UL

#define LXGR_PAGE_OFFSET 0xffffff8000000000ULL   /* 39-bit VA */
#define LXGR_USER_VA_TOP 0x8000000000ULL

#endif /* LXGR_KMOD_OFFSETS_H */
